# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/microprocessor_block/microprocessor_block.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microprocessor_block || ORIG_REF_NAME==microprocessor_block} -quiet] -quiet

# IP: bd/microprocessor_block/ip/microprocessor_block_processing_system7_0_0/microprocessor_block_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microprocessor_block_processing_system7_0_0 || ORIG_REF_NAME==microprocessor_block_processing_system7_0_0} -quiet] -quiet

# IP: bd/microprocessor_block/ip/microprocessor_block_axi_timer_0_0/microprocessor_block_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microprocessor_block_axi_timer_0_0 || ORIG_REF_NAME==microprocessor_block_axi_timer_0_0} -quiet] -quiet

# IP: bd/microprocessor_block/ip/microprocessor_block_auto_pc_0/microprocessor_block_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microprocessor_block_auto_pc_0 || ORIG_REF_NAME==microprocessor_block_auto_pc_0} -quiet] -quiet

# IP: bd/microprocessor_block/ip/microprocessor_block_ps7_0_axi_periph_0/microprocessor_block_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microprocessor_block_ps7_0_axi_periph_0 || ORIG_REF_NAME==microprocessor_block_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/microprocessor_block/ip/microprocessor_block_rst_ps7_0_50M_0/microprocessor_block_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microprocessor_block_rst_ps7_0_50M_0 || ORIG_REF_NAME==microprocessor_block_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: bd/microprocessor_block/microprocessor_block_ooc.xdc
